# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Figures.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from Task1 import *
class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.Photo = QtWidgets.QLabel(self.centralwidget)
        self.Photo.setGeometry(QtCore.QRect(140, 0, 431, 151))
        self.Photo.setObjectName("Photo")
        self.comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox.setGeometry(QtCore.QRect(190, 170, 311, 81))
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.CalculateArea = QtWidgets.QPushButton(self.centralwidget)
        self.CalculateArea.setGeometry(QtCore.QRect(30, 340, 121, 51))
        self.CalculateArea.setObjectName("CalculateArea")
        self.CalcText = QtWidgets.QLabel(self.centralwidget)
        self.CalcText.setGeometry(QtCore.QRect(190, 340, 401, 51))
        self.CalcText.setObjectName("CalcText")
        self.Retry = QtWidgets.QPushButton(self.centralwidget)
        self.Retry.setGeometry(QtCore.QRect(80, 440, 121, 41))
        self.Retry.setObjectName("Retry")
        self.Ignore = QtWidgets.QPushButton(self.centralwidget)
        self.Ignore.setGeometry(QtCore.QRect(260, 440, 121, 41))
        self.Ignore.setObjectName("Ignore")
        self.Cancel = QtWidgets.QPushButton(self.centralwidget)
        self.Cancel.setGeometry(QtCore.QRect(430, 440, 121, 41))
        self.Cancel.setObjectName("Cancel")
        self.Close = QtWidgets.QPushButton(self.centralwidget)
        self.Close.setGeometry(QtCore.QRect(610, 440, 121, 41))
        self.Close.setObjectName("Close")
        self.Show = QtWidgets.QPushButton(self.centralwidget)
        self.Show.setGeometry(QtCore.QRect(270, 280, 151, 28))
        self.Show.setObjectName("Show")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.Show.clicked.connect(self.f1)
        self.CalculateArea.clicked.connect(self.CalcAr)
        

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.Photo.setText(_translate("MainWindow", "Photo"))
        self.comboBox.setItemText(0, _translate("MainWindow", "Trapecia"))
        self.comboBox.setItemText(1, _translate("MainWindow", "Martkutxedi"))
        self.comboBox.setItemText(2, _translate("MainWindow", "Kvadrati"))
        self.CalculateArea.setText(_translate("MainWindow", "Calculate Area"))
        self.CalcText.setText(_translate("MainWindow", "Area is shown Here."))
        self.Retry.setText(_translate("MainWindow", "Retry"))
        self.Ignore.setText(_translate("MainWindow", "Ignore"))
        self.Cancel.setText(_translate("MainWindow", "Cancel"))
        self.Close.setText(_translate("MainWindow", "Close"))
        self.Close.clicked.connect(MainWindow.close)
        self.Show.setText(_translate("MainWindow", "Show Object photo"))

    def f1(self):
        lang = str(self.comboBox.currentText())
        if lang == "Trapecia":
            self.Photo.setPixmap(QtGui.QPixmap("trapecia.jpg"))
            self.Photo.adjustSize()
        elif lang == "Martkutxedi":
            self.Photo.setPixmap(QtGui.QPixmap("martkutxedi.jpg"))
            self.Photo.adjustSize()
        elif lang == "Kvadrati":
            self.Photo.setPixmap(QtGui.QPixmap("kvadrati.jpg"))
            
    def CalcAr(self):
        obj1 =tolperdaTrapecia([20,20,20])
        obj2 =martkutxedi([20,20,20])
        obj3 =kvadrati([20,20,20])


        lang = str(self.comboBox.currentText())
        if lang == "Trapecia":
            self.CalcText.setText(str(obj1.partobi()))
        elif lang == "Martkutxedi":
            self.CalcText.setText(str(obj2.partobi()))
        elif lang == "Kvadrati":
            self.CalcText.setText(str(obj3.partobi()))        
            
        
        
        

                    



if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
